---
- name: Install required dependencies
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Add New Relic GPG Key
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name: Add New Relic repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/newrelic-infra.gpg] https://download.newrelic.com/infrastructure_agent/linux/apt bullseye main"
    state: present
    filename: newrelic-infra

- name: Install New Relic Infrastructure Agent
  apt:
    name: newrelic-infra
    state: present
    update_cache: yes

- name: Configure New Relic Infrastructure Agent
  template:
    src: newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    owner: root
    group: root
    mode: '0644'

- name: Enable and start New Relic Infrastructure Agent
  systemd:
    name: newrelic-infra
    state: restarted
    enabled: yes
